In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [4]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [5]:
s = (2,2)

In [6]:
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [7]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')])

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])